import {
  Compass,
  Hand,
  BadgeDollarSign,
  AlertCircle,
  Flame,
  HeartHandshake,
  Wind,
  Anchor,
  ScanFace,
  Heart,
  BookHeart,
  Palmtree,
  Bed,
  Footprints,
  Dumbbell,
} from "lucide-react";

export const TESTS = [
  {
    key: "uncertainty_tolerance",
    title: "Умеете ли вы выдерживать неопределённость?",
    description: "Оцените, как вы реагируете на неопределённость и нестабильные ситуации.",
    time: "3–4 мин",
    tags: ["Тревога", "Устойчивость", "Самопознание"],
    Icon: Compass,
    accent: "from-blue-100 via-white to-purple-100",
  },
  {
    key: "manipulation_test",
    title: "Легко ли вами манипулировать?",
    description: "Оцените вашу устойчивость к манипуляциям и умение защищать личные границы.",
    time: "3–4 мин",
    tags: ["Отношения", "Границы", "Самопознание"],
    Icon: Hand,
    accent: "from-purple-100 via-white to-blue-100",
  },
  {
    key: "money_attitude",
    title: "Тест на отношение к деньгам",
    description: "Оцените ваши финансовые привычки и психологическое отношение к деньгам.",
    time: "3–4 мин",
    tags: ["Финансы", "Привычки", "Самопознание"],
    Icon: BadgeDollarSign,
    accent: "from-orange-100 via-white to-blue-100",
  },
  {
    key: "anxiety_gad7",
    title: "Тест на уровень тревожности (GAD-7)",
    description: "Оцените уровень тревоги за последние 2 недели. Клинический тест GAD-7.",
    time: "2–3 мин",
    tags: ["Тревога", "Самопознание", "Здоровье"],
    Icon: AlertCircle,
    accent: "from-red-100 via-white to-orange-100",
  },
  {
    key: "stress_test",
    title: "Тест на уровень стресса",
    description: "Оцените ваш текущий уровень стресса и получите персональные рекомендации.",
    time: "3–4 мин",
    tags: ["Стресс", "Самопознание", "Здоровье"],
    Icon: Flame,
    accent: "from-orange-100 via-white to-amber-100",
  },
  {
    key: "emotional_intelligence",
    title: "Тест на эмоциональный интеллект (EQ)",
    description: "Оцените вашу способность распознавать, понимать и управлять эмоциями.",
    time: "4–5 мин",
    tags: ["Эмоции", "Самопознание", "Отношения"],
    Icon: HeartHandshake,
    accent: "from-pink-100 via-white to-purple-100",
  },
  {
    key: "burnout_test",
    title: "Тест на профессиональное выгорание",
    description: "Оцените уровень эмоционального, физического и ментального истощения.",
    time: "3–4 мин",
    tags: ["Выгорание", "Работа", "Здоровье"],
    Icon: Flame,
    accent: "from-red-100 via-white to-orange-100",
  },
];

export const EXERCISES = [
  {
    key: "box_breathing",
    title: "Дыхание «Квадрат» (1–2 минуты)",
    why: "Снижает тревогу и выравнивает дыхание.",
    steps: ["Вдох 4", "Задержка 4", "Выдох 4", "Задержка 4", "Повтори 4 круга"],
    time: "1–2 минуты",
    tags: ["Дыхание", "Тревога"],
    Icon: Wind,
    accent: "from-blue-100 via-white to-purple-100",
  },
  {
    key: "5_4_3_2_1",
    title: "Заземление 5-4-3-2-1 (2 минуты)",
    why: "Возвращает в «здесь и сейчас» при стрессе.",
    steps: ["5 вещей вижу", "4 ощущаю", "3 слышу", "2 чувствую запах", "1 вкус/мысль"],
    time: "2 минуты",
    tags: ["Фокус", "Стресс"],
    Icon: Anchor,
    accent: "from-purple-100 via-white to-blue-100",
  },
  {
    key: "micro_body_scan",
    title: "Мини body scan (2 минуты)",
    why: "Снимает напряжение в теле.",
    steps: ["Лоб/челюсть расслабить", "Плечи вниз", "Дыхание мягко", "Стопы почувствовать"],
    time: "2 минуты",
    tags: ["Тело", "Напряжение"],
    Icon: ScanFace,
    accent: "from-orange-100 via-white to-purple-100",
  },
  {
    key: "4_7_8_breathing",
    title: "Дыхание 4-7-8 (2 минуты)",
    why: "Активирует парасимпатическую нервную систему, снижает тревогу.",
    steps: ["Выдох через рот со звуком", "Вдох через нос 4 сек", "Задержка 7 сек", "Выдох через рот 8 сек", "Повтори 4 цикла"],
    time: "2 минуты",
    tags: ["Дыхание", "Тревога", "Сон"],
    Icon: Wind,
    accent: "from-sky-100 via-white to-blue-100",
  },
  {
    key: "progressive_muscle_relaxation",
    title: "Прогрессивная мышечная релаксация (5 мин)",
    why: "Снимает мышечное напряжение и физические проявления стресса.",
    steps: ["Напряги стопы 5 сек → расслабь", "Икры → бёдра → живот", "Кулаки → плечи → шею", "Лицо: сморщи → расслабь всё тело"],
    time: "5 минут",
    tags: ["Тело", "Напряжение", "Релаксация"],
    Icon: Dumbbell,
    accent: "from-violet-100 via-white to-purple-100",
  },
  {
    key: "loving_kindness_meditation",
    title: "Медитация любящей доброты (3 мин)",
    why: "Развивает эмпатию, снижает негативные эмоции.",
    steps: ["Пожелай счастья себе", "Близкому человеку", "Нейтральному знакомому", "Трудному человеку", "Всем живым существам"],
    time: "3 минуты",
    tags: ["Медитация", "Эмпатия", "Отношения"],
    Icon: Heart,
    accent: "from-pink-100 via-white to-rose-100",
  },
  {
    key: "gratitude_journal",
    title: "Дневник благодарности (3 минуты)",
    why: "Перепрограммирует мозг на поиск позитивного.",
    steps: ["Запиши 3 вещи благодарности", "Будь конкретен", "Добавь эмоцию", "Делай 21 день подряд", "Перечитывай в трудные моменты"],
    time: "3 минуты",
    tags: ["Позитив", "Привычки", "Рефлексия"],
    Icon: BookHeart,
    accent: "from-amber-100 via-white to-yellow-100",
  },
  {
    key: "safe_place_visualization",
    title: "Визуализация безопасного места (4 мин)",
    why: "Создаёт внутренний ресурс для успокоения в стрессе.",
    steps: ["Представь безопасное место", "Что видишь? Детали цвета", "Что слышишь? Звуки", "Что ощущаешь? Тепло, запах", "Побудь там 2-3 минуты"],
    time: "4 минуты",
    tags: ["Визуализация", "Стресс", "Тревога"],
    Icon: Palmtree,
    accent: "from-emerald-100 via-white to-teal-100",
  },
  {
    key: "autogenic_training",
    title: "Автогенная тренировка (5 минут)",
    why: "Глубокая релаксация через самовнушение.",
    steps: ["'Моя рука тяжёлая и тёплая'", "'Обе ноги тяжёлые и тёплые'", "'Моё дыхание спокойное'", "'Моё сердцебиение спокойное'", "'Тело расслаблено'"],
    time: "5 минут",
    tags: ["Релаксация", "Самовнушение", "Глубокий отдых"],
    Icon: Bed,
    accent: "from-indigo-100 via-white to-violet-100",
  },
  {
    key: "mindful_walking",
    title: "Осознанная прогулка (5-10 минут)",
    why: "Снижает руминацию (навязчивые мысли).",
    steps: ["Иди медленно без телефона", "Почувствуй стопы на земле", "Заметь движение ног, рук, дыхание", "Если отвлёкся → верни внимание", "Наблюдай цвета, звуки, запахи"],
    time: "5-10 минут",
    tags: ["Mindfulness", "Движение", "Осознанность"],
    Icon: Footprints,
    accent: "from-green-100 via-white to-lime-100",
  },
];
